### ISSUE TITLE
Issue 1: User can search for a specific brewery by name

### ISSUE THREAD

**Issue by nimcastano** [nimcastano/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for a specific brewery by name
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Typing the name of a brewery into the input text box will return a list of matching breweries.
User should be able to see 3 breweries per page and can turn to next page if necessary.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="234" alt="Screenshot 2023-04-27 at 10 26 12 AM" src="https://user-images.githubusercontent.com/126118228/234941743-e86b05a9-d198-4b11-b9ce-3bd7aaa470c5.png">
<img width="242" alt="Screenshot 2023-04-27 at 10 26 25 AM" src="https://user-images.githubusercontent.com/126118228/234941748-d0b61e5d-21fe-40d1-824a-a94b0283af67.png">
<img width="790" alt="Screenshot 2023-04-27 at 2 29 22 PM" src="https://user-images.githubusercontent.com/126118228/234995567-445d62a3-2e6a-419f-9f74-a6beecdf3fc6.png">
<img width="794" alt="Screenshot 2023-04-27 at 2 32 46 PM" src="https://user-images.githubusercontent.com/126118228/234996054-9036c101-cecc-431f-a3d7-95ed07314b67.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Design the home page to look like the figma
- [x]  Make form
- [x] Add functionality to form element with the brewery name text box
- [x] Make a function that creates a new XMLHttpRequest when submitted
- [x] use open method with GET and the URL for the brewery API
- [x] add an event listener for load and the function should log the status and response
- [x] then send the request with send method
- [x] the list of elements should append to the DOM as shown in the figma
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
