### ISSUE TITLE
Issue 2: User can get provided with a random brewery

### ISSUE THREAD

**Issue by nimcastano** [nimcastano/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can get provided with a random brewery.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
At the push of a button on the home page, the user will be provided a random brewery.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="213" alt="Screenshot 2023-04-27 at 4 35 16 PM" src="https://user-images.githubusercontent.com/126118228/235012457-a9ba1ad1-547b-4652-be72-3ecf5df50651.png">

<img width="790" alt="Screenshot 2023-04-27 at 4 35 03 PM" src="https://user-images.githubusercontent.com/126118228/235012415-128dfc87-c2c5-48d3-a069-d2d7ce264acd.png">
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a page that matches the figma
- [x] Add an event listener to the yellow button on the home page
- [x] It should create a ul element, class br-random-list, and have an li append to it
- [x] Make a new XMLHttpRequest with the random endpoint
- [x] Add it to li by reusing the render brewery function to add the random element to the DOM tree
- [x] Test the functionality of the button
- [x] Make sure the new ul gets removed from DOM when header anchor gets clicked
- [x] test both features so far
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
