### ISSUE TITLE
Issue 3: User can search for a list of breweries based on city

### ISSUE THREAD

**Issue by nimcastano** [nimcastano/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for a list of breweries based on the city.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
The user can type in a city and they will be sent to a page listing the breweries in that city.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="222" alt="Screenshot 2023-05-01 at 3 58 01 PM" src="https://user-images.githubusercontent.com/126118228/235545837-bb7202c9-822d-4723-9a14-1be17e344c06.png">

<img width="803" alt="Screenshot 2023-05-01 at 3 57 47 PM" src="https://user-images.githubusercontent.com/126118228/235545784-d7968995-c80d-4d38-8b47-e0907129a631.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add HTML and CSS to match the figma
- [x] Add an event listener to the city search input textbox
- [x] Make a new XMLHttpRequest to the API
- [x] make sure the event listener returns the correct data from the API
   - [x] Console.log the xhr.response to ensure this
   - [x] Append the returned data into the DOM using renderBrList
   - [x] check the DOM in inspect to ensure it is properly appended into the DOM
- [x] Remove the appended DOM elements from the API  whenever you exit the page
- [x] Make sure it hides the other pages when the event is fired
- [x] check on the other features to make sure they still work
- [x] check that there are no errors in the console
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
