### ISSUE TITLE
Issue 4: User can save breweries for future reference

### ISSUE THREAD

**Issue by nimcastano** [nimcastano/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save breweries for future reference.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
After searching for breweries, user can click on the plus sign next to the brewery listing to add it to his favorites. This page can be accessed by the saved breweries list button on the home page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="174" alt="Screenshot 2023-05-03 at 10 05 38 AM" src="https://user-images.githubusercontent.com/126118228/235989657-4630a3f4-eff6-41e4-beb8-e3c89a357699.png">
<img width="235" alt="Screenshot 2023-05-03 at 10 06 39 AM" src="https://user-images.githubusercontent.com/126118228/235989699-892b5e27-1837-4f9f-aa83-d8b628c9b603.png">
<img width="412" alt="Screenshot 2023-05-03 at 10 06 00 AM" src="https://user-images.githubusercontent.com/126118228/235989730-1ead5151-fa0c-4ac8-9805-fb398f6b9c8a.png">
<img width="427" alt="Screenshot 2023-05-03 at 10 06 17 AM" src="https://user-images.githubusercontent.com/126118228/235989737-acb16c46-7da3-491d-bcee-c7b80843bb32.png">
<img width="218" alt="Screenshot 2023-05-03 at 10 08 03 AM" src="https://user-images.githubusercontent.com/126118228/235989774-2d925587-74b6-49c3-88d6-62b53638afbe.png">
<img width="802" alt="Screenshot 2023-05-03 at 10 08 10 AM" src="https://user-images.githubusercontent.com/126118228/235989779-7bee06e7-2c9e-4e38-a11c-0f15fddee6ef.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a container and page in the html for the favorites page that matches the figma
     - [x] look for the image and add it to the html to match
     - [x] add a ul element and give it a ID name of faves-list
- [x] Add a modal in html and center it to match the figma in the name-page, random-page, and the city-page
- [x] Add a grey overlay over the screen that does not affect the modal
- [x] Add an eventlistener to the plus signs that make the modal pop up if clicked on
- [x] Add an eventlistener to the nope button that hides the modal if clicked on
- [x] Add the data object in data.js that has an entries array for the favorites
- [x] Add an eventlistener to the add it button
    - [x] query the closest li item to the plus button that was clicked before
    - [x] it should add the closest entry to the data.entries array
- [x] add an eventlistener to the saved breweries list on the home-page
    - [x] have the data.entries array go through the renderBrList
    - [x] append each li element to the ul in the faves-page
- [x] check to see that it is actually being appended on the faves-page
- [x] make sure the list matches the figma
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
