### ISSUE TITLE
Issue 5: User can delete breweries from future reference

### ISSUE THREAD

**Issue by nimcastano** [nimcastano/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete breweries from their favorites list
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on the minus symbol next to the brewery name and will be given an option to delete the brewery from their favorites list. If they do so, it will not show up from the list.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="693" alt="Screenshot 2023-05-04 at 12 02 13 PM" src="https://user-images.githubusercontent.com/126118228/236303389-20f102c9-e728-4f71-81a2-7266d013038c.png">
<img width="1135" alt="Screenshot 2023-05-04 at 12 01 56 PM" src="https://user-images.githubusercontent.com/126118228/236303414-48f97650-068e-4f66-a38f-56b795ab3f03.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a parameter minus to the renderEntry function
     - [x] add a condition if (minus) that puts a fa-minus instead of the plus next to br name
     - [x] give it a class of minus for future functionality
- [x] Add a modal to html that matches figma for entry deletion
- [x] add an event listener to the minus
     - [x] should unhide the modal
- [x] add an event listener if nope is clicked, hides the modal
- [x] add an event listener if confirm retirement is clicked
     - [x] get the className of closest li element
     - [x] create for loop for data.entries and splice it out of the array
- [x] check and recheck feature to make sure that it does actually delete the entry
- [x] check all features are still functional
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
